import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import '../../core/api_client.dart';
import '../../models/story.dart';
import '../../state/app_state.dart';
import '../../state/history_recorder.dart';
import '../../widgets/states_view.dart';
import '../../widgets/stories_pager.dart';
import '../main_shell.dart';
import '../router.dart';

/// The vertical-video rail.
///
/// Shorts are generated by the newsroom from published stories; the format is
/// optional and a story without one is simply not shown here. When nothing is
/// available the screen says so plainly rather than fabricating clips.
class ShortsPage extends StatefulWidget {
  const ShortsPage({super.key});

  @override
  State<ShortsPage> createState() => _ShortsPageState();
}

class _ShortsPageState extends State<ShortsPage> {
  final PageController _controller = PageController();
  List<Story> _stories = [];
  bool _loading = true;
  String? _error;
  String? _lastLocale;

  @override
  void didChangeDependencies() {
    super.didChangeDependencies();
    final locale = context.read<AppState>().locale;
    if (_lastLocale != locale) {
      _lastLocale = locale;
      _load();
    }
  }

  Future<void> _load() async {
    final app = context.read<AppState>();
    setState(() {
      _loading = true;
      _error = null;
    });
    try {
      final page = await app.api.feed(
        language: app.locale,
        page: 1,
        pageSize: 40,
      );
      if (!mounted) return;
      // Only stories the newsroom actually produced a short for.
      final shorts = page.items.where(_hasShort).toList();
      setState(() {
        _stories = shorts;
        _loading = false;
      });
    } on ApiException catch (exc) {
      if (!mounted) return;
      setState(() {
        _error = exc.message;
        _loading = false;
      });
    }
  }

  /// A short is signalled by a poster frame plus the media entry. The feed
  /// does not yet carry a dedicated flag, so we infer from the media kinds the
  /// newsroom can serve.
  bool _hasShort(Story story) {
    return story.imageUrl != null && (story.hasAudio || story.isBreaking);
  }

  @override
  Widget build(BuildContext context) {
    final app = context.watch<AppState>();
    final strings = app.strings;
    if (_loading) {
      return TabScaffold(title: strings.shorts, body: const LoadingView());
    }
    if (_error != null) {
      return TabScaffold(
        title: strings.shorts,
        body: ErrorState(
          message: _error!,
          onRetry: _load,
          offlineHint: true,
        ),
      );
    }
    if (_stories.isEmpty) {
      return TabScaffold(
        title: strings.shorts,
        body: EmptyState(
          title: strings.feedEmpty,
          hint: strings.feedEmptyHint,
          icon: Icons.smart_display_outlined,
          actionLabel: strings.retry,
          onAction: _load,
        ),
      );
    }
    return Scaffold(
      appBar: AppBar(
        title: Text(strings.shorts,
            style: const TextStyle(fontWeight: FontWeight.w800)),
        actions: const [LanguageButton()],
      ),
      body: ShortsPager(
        controller: _controller,
        stories: _stories,
        onOpenStory: (story) {
          context.read<HistoryRecorder>().start(story.id);
          Navigator.pushNamed(context, DashaRouter.story,
              arguments: StoryDetailArgs(story: story));
        },
      ),
    );
  }
}
